<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "member".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $email
 * @property string $tel
 * @property integer $last_login_time
 * @property integer $last_login_ip
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class Member extends \yii\db\ActiveRecord
{
    const SCENARIO_REGISTER = 'register';

    public $code;//图像验证码
    public $smsCode;//短信验证码
    public $password;//密码
    public $rePassword;//确认密码
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'member';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username','tel','email'], 'required'],
            [['code','smsCode','password','rePassword'], 'required','on'=>self::SCENARIO_REGISTER],
            [['code'], 'captcha','on'=>self::SCENARIO_REGISTER],
            [['last_login_time', 'last_login_ip', 'status', 'created_at', 'updated_at'], 'integer'],
            [['username'], 'string', 'max' => 50],
            [['auth_key'], 'string', 'max' => 32],
            [['password_hash', 'email'], 'string', 'max' => 100],
            [['tel'], 'string', 'max' => 11],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '用户名',
            'auth_key' => 'Auth Key',
            'password_hash' => '密码',
            'email' => '邮箱',
            'tel' => '电话',
            'last_login_time' => '最后登录时间',
            'last_login_ip' => '最后登录ip',
            'status' => 'status',
            'created_at' => '添加时间',
            'updated_at' => '修改时间',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->auth_key = Yii::$app->security->generateRandomString();
            $this->created_at = time();
            $this->status = 1;
        }else{
            $this->updated_at = time();
        }
        if($this->password) $this->password_hash = Yii::$app->security->generatePasswordHash($this->password);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
